### PR TITLE
Make update_push_items accept keyword arguments

### PR DESCRIPTION
**Pull request by JayZ12138**

### CODE REVIEW

**Comment by JayZ12138** [comment]
version of coverage is locked to 4.5.4. The new version 5.0.0 is not compatible with coveralls 1.9.2

**Comment by negillett** [comment]
What issue is this for?

**Comment by JayZ12138** [comment]
> What issue is this for?

This is for DELIVERY-5886. I plan to get all items with the same name and update in batch after push if it's a nochannle push. So, I need to pass extra arg to let it know it's a nochannel push.

**Review by negillett — APPROVED** [review]
Looks good assuming there's some code incoming to use the kwarg. Having the JIRA ID in the commit subject would be nice, though.

**Review by rohanpm — CHANGES_REQUESTED** [review]
Can you explain a bit more why this is needed?  It doesn't make sense to me.  How is it meant to be used, under what circumstances should the caller pass nochannel and under what circumstances should they not?  Can you explain that in the docs?

I kinda doubt this is needed, because in the crashing issue you're trying to resolve, the push items are not truly duplicates, are they?  Only a subset of their attributes are duplicates.  So it seems like the crash ought to be resolvable without adding hacks like this to the API.

Also, if it really was needed, I don't think we should keep using the term "nochannel" here just because the legacy tools used it.

**Comment by JayZ12138** [comment]
> Can you explain a bit more why this is needed? It doesn't make sense to me. How is it meant to be used, under what circumstances should the caller pass nochannel and under what circumstances should they not? Can you explain that in the docs?
> 
> I kinda doubt this is needed, because in the crashing issue you're trying to resolve, the push items are not truly duplicates, are they? Only a subset of their attributes are duplicates. So it s eems like the crash ought to be resolvable without adding hacks like this to the API.
> 
> Also, if it really was needed, I don't think we should keep using the term "nochannel" here just because the legacy tools used it.

I think we don't need this anymore because the duplicate items should have different sources as we discussed before in that JIRA. I'm closing this one.

**Pull request closed without merging**
